---
version: "2"
linters:
  default: all
  disable:
    - gomodguard
    - wsl
    - depguard
    - tagliatelle
    - nolintlint
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    - noinlineerr
    # replaced by exhaustruct_v5 since golangci-lint v2.13.0
    - exhaustruct
