---
linters:
  enable-all: true
  disable:
    - depguard
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
    - exhaustivestruct
    - deadcode
    - varcheck
    - nosnakecase
    - ifshort
    - structcheck
