---
version: "2"
linters:
  default: all
  disable:
    - gomodguard
    - wsl
    - depguard
    - tagliatelle
    - nolintlint
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    - noinlineerr
