package urlsvc

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/1995parham-teaching/tinyurl/internal/domain/model/url"
	"github.com/1995parham-teaching/tinyurl/internal/domain/repository/urlrepo"
	"github.com/1995parham-teaching/tinyurl/internal/infra/generator"
	"go.uber.org/zap"
)

var (
	ErrKeyGenFailed     = errors.New("cannot generate new random string as short url")
	ErrKeyAlreadyExists = errors.New("given key already exists")
	ErrURLNotFound      = urlrepo.ErrURLNotFound
)

type URLSvc interface {
	Create(ctx context.Context, address string, expire *time.Time) (string, error)
	CreateWithKey(ctx context.Context, key string, address string, expire *time.Time) error
	Visit(ctx context.Context, key string) (url.URL, error)
}

type urlSvc struct {
	repo   urlrepo.Repository
	logger *zap.Logger
	gen    generator.Generator
}

func ProvideURLSvc(repo urlrepo.Repository, logger *zap.Logger, gen generator.Generator) URLSvc {
	return &urlSvc{
		gen:    gen,
		repo:   repo,
		logger: logger.Named("urlsvc"),
	}
}

// MaxKeyGenAttempts bounds how many keys Create will try before giving up. Generators that
// build unique keys by construction never collide, and for random ones the expected number of
// attempts is 1/(1-load factor) — so this is only ever reached once the key space is nearly full.
const MaxKeyGenAttempts = 5

func (s *urlSvc) Create(ctx context.Context, address string, expire *time.Time) (string, error) {
	for attempt := range MaxKeyGenAttempts {
		key, err := s.gen.ShortURLKey(ctx)
		if err != nil {
			return "", fmt.Errorf("short url key generation failed %w", err)
		}

		err = s.create(ctx, key, address, expire)
		if err == nil {
			return key, nil
		}

		if !errors.Is(err, urlrepo.ErrDuplicateShortURL) {
			return "", err
		}

		s.logger.Warn("short url key already taken, generating another one",
			zap.String("key", key), zap.Int("attempt", attempt+1))
	}

	return "", ErrKeyGenFailed
}

// CreateWithKey stores a url under a name the caller chose.
//
// Chosen names share a key space with generated ones. Nothing keeps them apart because nothing
// needs to: the primary key rejects a name that is taken, and a generated key that happens to
// land on one is simply regenerated by Create. Keeping one key space means a lookup is one
// query rather than a query per kind of key.
func (s *urlSvc) CreateWithKey(ctx context.Context, key string, address string, expire *time.Time) error {
	if err := s.create(ctx, key, address, expire); err != nil {
		if errors.Is(err, urlrepo.ErrDuplicateShortURL) {
			return ErrKeyAlreadyExists
		}

		return err
	}

	return nil
}

func (s *urlSvc) Visit(ctx context.Context, key string) (url.URL, error) {
	url, err := s.repo.FromShortURL(ctx, key)
	if err != nil {
		if errors.Is(err, urlrepo.ErrURLNotFound) {
			return url, ErrURLNotFound
		}

		return url, fmt.Errorf("url fetching failed %w", err)
	}

	// counting a visit must never keep a redirect waiting, and must never fail one either: the
	// repository decides whether that means a write now or a counter folded into a later batch.
	if err := s.repo.IncrementVisits(ctx, url.Key); err != nil {
		s.logger.Error("incrementing url visit count failed", zap.Error(err))
	}

	// the visit count is deliberately returned as it was read. Counts are batched and reads are
	// cached, so anything computed here would be a guess dressed up as a total; nothing serves
	// this field, and a caller who needs the real number should ask the database for it.

	return url, nil
}

func (s *urlSvc) create(ctx context.Context, key string, address string, expire *time.Time) error {
	valid := true

	if expire == nil {
		expire = new(time.Time)
		valid = false
	}

	// nolint: exhaustruct_v5
	url := url.URL{
		Key:    key,
		URL:    address,
		Visits: 0,
		Expire: sql.NullTime{
			Time:  *expire,
			Valid: valid,
		},
	}

	if err := s.repo.Create(ctx, url); err != nil {
		return fmt.Errorf("url creation failed %w", err)
	}

	return nil
}
